name: Deploy to Alwaysdata

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP/SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.alwaysdata.com
          username: ${{ secrets.AD_USER }}
          password: ${{ secrets.AD_PASSWORD }}
          local-dir: ./
          server-dir: /home/yourusername/www/yeadonaye/
          protocol: sftp
          dry-run: false
